"""
search_wikipedia skill — auto-generated from TOOL_DEFINITIONS.

Wraps the existing search.wikipedia capability. Behavior is unchanged from the
pre-migration hardcoded handler in brain/agentic/tool_schemas.py.

Generated by scripts/migrate_tools_to_skills.py — feel free to edit by hand
once it's in your repo. Re-running the migration script will skip this file
because the folder already exists.
"""
from __future__ import annotations


def handle(query: str, **_) -> str:
    from capabilities.registry import REGISTRY
    cap = REGISTRY.get("search.wikipedia")
    if cap is None:
        return "[error] search.wikipedia not registered"
    return cap.handler(raw_text=query, entities={query: "MISC"})
