"""
get_weather skill — auto-generated from TOOL_DEFINITIONS.

Wraps the existing weather.get_for_city capability. Behavior is unchanged from the
pre-migration hardcoded handler in brain/agentic/tool_schemas.py.

Generated by scripts/migrate_tools_to_skills.py — feel free to edit by hand
once it's in your repo. Re-running the migration script will skip this file
because the folder already exists.
"""
from __future__ import annotations


def handle(city: str, day_offset: int = 0, **_) -> str:
    from capabilities.registry import REGISTRY
    cap = REGISTRY.get("weather.get_for_city")
    if cap is None:
        return "[error] weather.get_for_city not registered"
    return cap.handler(city=city, day_offset=day_offset)
