"""
get_flight_status skill — auto-generated from TOOL_DEFINITIONS.

Wraps the existing flights.get_for_number capability. Behavior is unchanged from the
pre-migration hardcoded handler in brain/agentic/tool_schemas.py.

Generated by scripts/migrate_tools_to_skills.py — feel free to edit by hand
once it's in your repo. Re-running the migration script will skip this file
because the folder already exists.
"""
from __future__ import annotations


def handle(flight_number: str, **_) -> str:
    from capabilities.registry import REGISTRY
    cap = REGISTRY.get("flights.get_for_number")
    if cap is None:
        return "[error] flights.get_for_number not registered"
    return cap.handler(flight_number=flight_number)
