"""
get_news skill — auto-generated from TOOL_DEFINITIONS.

Wraps the existing news.get_headlines capability. Behavior is unchanged from the
pre-migration hardcoded handler in brain/agentic/tool_schemas.py.

Generated by scripts/migrate_tools_to_skills.py — feel free to edit by hand
once it's in your repo. Re-running the migration script will skip this file
because the folder already exists.
"""
from __future__ import annotations


def handle(**_) -> str:
    from capabilities.registry import REGISTRY
    cap = REGISTRY.get("news.get_headlines")
    if cap is None:
        return "[error] news.get_headlines not registered"
    return cap.handler()
