"""
close_app skill — auto-generated from TOOL_DEFINITIONS.

Wraps the existing desktop.close_app capability. Behavior is unchanged from the
pre-migration hardcoded handler in brain/agentic/tool_schemas.py.

Generated by scripts/migrate_tools_to_skills.py — feel free to edit by hand
once it's in your repo. Re-running the migration script will skip this file
because the folder already exists.
"""
from __future__ import annotations


def handle(app_name: str, **_) -> str:
    from capabilities.registry import REGISTRY
    cap = REGISTRY.get("desktop.close_app")
    if cap is None:
        return "[error] desktop.close_app not registered"
    return cap.handler(raw_text=f"close {app_name}", followup_answer=app_name)
