"""
get_crypto_price skill — auto-generated from TOOL_DEFINITIONS.

Wraps the existing crypto.get_for_coin capability. Behavior is unchanged from the
pre-migration hardcoded handler in brain/agentic/tool_schemas.py.

Generated by scripts/migrate_tools_to_skills.py — feel free to edit by hand
once it's in your repo. Re-running the migration script will skip this file
because the folder already exists.
"""
from __future__ import annotations


def handle(coin: str, **_) -> str:
    from capabilities.registry import REGISTRY
    cap = REGISTRY.get("crypto.get_for_coin")
    if cap is None:
        return "[error] crypto.get_for_coin not registered"
    return cap.handler(coin=coin)
